version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Instalando Maven"
      - mvn --version
  build:
    commands:
      - echo "Rodando build Maven"
      - mvn clean install

artifacts:
  files:
    - target/*.jar
