name: Deploy to AWS

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar autenticação com AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::214882929875:role/GitHubActionsDeployRole
          aws-region: sa-east-1

      - name: Verificar versão do Java
        run: java -version

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Login no ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir e push da imagem Docker
        env:
          ECR_REGISTRY: 214882929875.dkr.ecr.sa-east-1.amazonaws.com
          IMAGE_NAME: iam-client-registry-service
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest
