name: Deploy no ECR via OIDC

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar autenticação com a AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::214882929875:role/GitHubActionsDeployRole
          aws-region: sa-east-1

      - name: Login no Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build da imagem Docker
        run: |
          docker build -t iam-client-registry-service .
          docker tag iam-client-registry-service:latest 214882929875.dkr.ecr.sa-east-1.amazonaws.com/iam-client-registry-service:latest

      - name: Push para o Amazon ECR
        run: |
          docker push 214882929875.dkr.ecr.sa-east-1.amazonaws.com/iam-client-registry-service:latest
